### ISSUE TITLE
[Bug Report]: Cannot synchronize multiple proxy sanctions

### ISSUE THREAD

**Issue by DoctaEnkoda** [A248/LibertyBans#100]
### LibertyBans Version

LibertyBans 0.8.1

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Velocity

### Description

We have 2 proxies, and the sanctions made on proxy A are not applied on proxy B (warn / mute / kick / ban). The player must log out for the sanction to take place.

Database: MariaDB
Velocity: 3.1.1

**Comment by KoxSosen** [comment]
Hello!

Could you please ensure that `expiration-semantics` is set to `EXPIRE_AFTER_WRITE` in the `sql.yml` file? 

Also, please see #44 .

**Comment by A248** [comment]
The current limitation of multi-proxy support in LibertyBans confines its application as follows:

* Place LibertyBans on each backend server, rather than on the proxy
* Configure the same database
* You will be able to ban, mute, warn, and kick players on the same backend server as yourself. If you try to ban, mute, or warn a player on another server, the ban will take effect once the player logs out, mutes will take effect after cache expiration (see Simon's comment), and warns will take effect immediately. Kicks are not possible

This limitation will be lifted in LibertyBans 1.0.0, which is scheduled for 25 December. Once 1.0.0 is released, you will be able to use the aforementioned setup, without the limitation described in the last bullet point. The tracking issue is #44 .
