### ISSUE TITLE
[Feature Request]: Allow to show all punishments on /blame

### ISSUE THREAD

**Issue by YoSoyVillaa** [A248/LibertyBans#110]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

I know that removing past punishments from `/blame` command reduce load time and pruduces less performent impact. But sometimes the staff manager or other staff member requires on check all the punishments a staff member made.

I think `/blame` is the only command that have this _"problem"_, it could be great if you could choose to show or not all punishments.

**Comment by A248** [comment]
This feature suggestion pairs nicely with the staff rollback addon, since it makes `/blame` consistent with the punishments which would be covered by a staff rollback operation.

For your information, performance impact isn't an issue here. Commands run asynchronously, database queries are indexed, and most database load comes from checking incoming players for applicable bans, not from commands.
