### ISSUE TITLE
[Feature Request]: PunishmentExpirationEvent

### ISSUE THREAD

**Issue by BlueTree242** [A248/LibertyBans#114]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Please add this event in the api, we need it. Its very important in my case, thanks!

**Comment by A248** [comment]
As I have previously explained to you, firing this event would require undue technical resources.

It is possible for punishments to expire every second. As such, in order to implement this event correctly, we would need to fire a database query each second to determine which punishments are expiring at the current moment (It would also be possible to use an interval, say five seconds, in which punishments are deemed to have expired, to lessen the performance impact).

In any case this is not an event best implemented in LibertyBans. Adding it correctly would require taking on an additional database load equivalent to what a medium-size proxy would experience in the absence of this feature. However, if you need this event, you can implement it yourself, by polling the database in the fashion I have described.
