### ISSUE TITLE
[Bug Report]: error using aegis

### ISSUE THREAD

**Issue by craciu25yt** [A248/LibertyBans#123]
### LibertyBans Version

1.0

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Bungeecord

### Description

![image](https://user-images.githubusercontent.com/48807342/149916279-18b46f87-d8d6-4230-970f-71f001cb14e8.png)

**Comment by BlueTree242** [comment]
Normally this isn't a bug, its a conflict with another plugin whose author never relocated, but since this is a bungeecord fork i think you should try libertybans alone without any other plugins

**Comment by KoxSosen** [comment]
It seems like that Aegis may bundle HikariCP without relocating it. I'm saying *may* because it's proprietary software, and we can't verify if this is true or not.

However compatibility for LibertyBans with all kinds of software is important, so I'm leaving this issue open in case A248, or someone has to say something.

Futhermore, please report this issue to the Aegis developers.
