### ISSUE TITLE
[Feature Request]: Add new Contexts to LuckPerms

### ISSUE THREAD

**Issue by ahdg6** [A248/LibertyBans#133]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

It would be nice to add punishment related contexts to LuckPerms, then we can deny a permission for certain player when he is muted, warned or something else.
![图片](https://user-images.githubusercontent.com/36436808/153252824-0174a4cc-f808-4fe1-90a5-45f675bf6178.png)
Related Documentation: https://luckperms.net/wiki/Developer-API-Usage#the-basics-of-context

**Comment by BlueTree242** [comment]
I guess they could just add placeholderapi support and there is a lp addon that creates contexts from placeholderapi

**Comment by ahdg6** [comment]
> I guess they could just add placeholderapi support and there is a lp addon that creates contexts from placeholderapi

Placeholders don't even exist on some platforms. Considering LibertyBans is a multi-platform plugin, hook into LuckPerms will be the best way.

**Comment by ahdg6** [comment]
> Can this be implemented using the LibertyBans API? I believe it can be.
> 
> I'd rather have this functionality be implemented by a dependent plugin. It should be rather simple to do.

It is because this is a simple feature, so it is more suitable for integrated into plugin.
No one wants to see every platform have an extra plug-in to extend this functionality as LuckPerms has a common API.

**Comment by A248** [comment]
There isn't anything wrong with having an extra plugin installed - it costs near-to-zero in terms of performance. You should be willing to have small, effective plugins whose sole purpose is to integrate the functionality of other plugins through well-defined APIs.

At the most, I would be willing to entertain this functionality as an addon using the planned addon system (#46), rather than as part of the core plugin.

**Comment by ahdg6** [comment]
>At the most, I would be willing to entertain this functionality as an addon using the planned addon system (https://github.com/A248/LibertyBans/issues/46), rather than as part of the core plugin.

New addon system is great for these things, looking forward to it.

**Comment by A248** [comment]
I started looking into this using the LuckPerms API. However, there is a structural/API issue here. LuckPerms requires contexts to be readily available. More specifically, context calculators must supply contexts immediately, and can't perform database queries. This would require LibertyBans to cache punishment data in-memory, in order to serve context calculation requests.

There was a similar issue with PlaceholderAPI. Because PlaceholderAPI requests placeholders immediately, and doesn't allow database queries, LibertyBans would need to add expansive caching in order to integrate with PlaceholderAPI.

In both of these cases, the best option is for someone to create an external plugin using the LibertyBans API. Caching decisions can (and should) be made in an external plugin, instead -- if you'd like me to elaborate on this, I am willing. With PlaceholderAPI, @BlueTree242 made a hook for LibertyBans and decided on a caching strategy. Someone should do the same for LuckPerms contexts.
