### ISSUE TITLE
[Feature Request]: Punishment templates

### ISSUE THREAD

**Issue by fabianmakila** [A248/LibertyBans#197]
### I have confirmed that ...

- [X] There is no duplicate feature request.

This might be somewhat related to #180

### Description

I'd like to propose the addition of punishment templates to LibertyBans.

The idea of templates is to speed up commonly occurring punishments like griefing, spamming, hacking etc.
Templates would also help to ensure a better consistency in given punishments by different staff members by providing a set of predefined punishments.

The templates could include the following:
- Predefined list of punishment reasons to choose from
- Ability to define the punishment length and type based on previous punishment history.

When calculating the punishment length/type it'd be nice if you could configure the template to either take the whole player history into account or just the previous punishments of the same type. Though I'm not sure how much it would introduce complicity to the template configuration.

The command for this could look something like this `/punish <player> <template-reason>`

Please do note that I'm not personally super familiar of how templates are implemented in other punishment plugins, so I won't go too deep on how the implementation of this could actually work.

**Comment by A248** [comment]
I believe this feature request is the same as #180 . However, I love your explanation because it tells me exactly how this feature should work and what decisions need to be made in implementing it. Since the other issue is more popular (based on upvotes), I will close this one, but repost your message there. Thank you for the detailed articulation; it is vastly appreciated.
