### ISSUE TITLE
[Feature Request]: Notify players when action happens to them

### ISSUE THREAD

**Issue by Boy0000** [A248/LibertyBans#198]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Basically send a message to a player if they are online that they got a punishment. Believe this already happens
Would also like for an option to send a player a message regarding punishments that have happened since they were last online.
Not sure if this is within the scope of the main plugin, or if it would be in an addon

**Comment by A248** [comment]
> Basically send a message to a player if they are online that they got a punishment. Believe this already happens

Yes, this already happens for warns and mutes.

> Would also like for an option to send a player a message regarding punishments that have happened since they were last online.
> Not sure if this is within the scope of the main plugin, or if it would be in an addon

This feature can be entirely implemented in a separate plugin using the LibertyBans API. I'd suggest you find a developer who is willing to create such a plugin. If you want it for free, you can tempt the developer by telling them that they could add support for multiple punishment plugins, increasing the appeal of their plugin (though you only need it for LibertyBans).

The feature would only make sense for warns, of course. However, it requires additional state tracking, which is why we won't be implementing it inside an addon.

**Comment by A248** [comment]
I'm closing this issue, because as mentioned, offline-punishment notifications should be done with the API.
