### ISSUE TITLE
Cant open Addons Website

### ISSUE THREAD

**Issue by RedCrafterHD** [A248/LibertyBans#250]
Hey, wanted to use LibertyBans on my MC server, but when I wanted to download some addons I needed, I ran into the problem, that I cant open the website, even after multiple tries spread over an hour. Dont know if you administrate the website or if you just use it, but could you please look into it?
Thanks in advance!
![grafik](https://github.com/A248/LibertyBans/assets/86547573/988d49fd-bacd-492e-934d-51c640ff3247)

**Comment by A248** [comment]
I believe the website is temporarily down for maintenance today. @KoxSosen can tell you more.

**Comment by KoxSosen** [comment]
Thank you for reporting! Apologies for the inconvenience, as A248 mentioned, the server hosting the Jenkins instance is temporary down for maintenance today, due to electricity work. I have access to a backups of all of our data from right before them going down, so if the service does not come back in the next 24 hours, I'll manually pull a copy of all addons, and post it here. Again, I apologize for any inconvenience/delay caused by this, however this is not something I could've "avoided".

**Comment by KoxSosen** [comment]
Everything should be back up, and operational as normal. Again, I apologize for the inconvenience this has caused.
