### ISSUE TITLE
[Feature Request]: Repair misunderstanding architecture

### ISSUE THREAD

**Issue by Dev1lroot** [A248/LibertyBans#265]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Using the word `victim` to refer to a criminal in a database architecture creates the impression that all the bans issued are issued by crazy dictators, this is not politically correct. I suggest using the word `criminal` as a column for a banned player. So far it looks like this plugin was developed by the Chinese party itself.

**Comment by gepron1x** [comment]
Must be a joke?

**Comment by JosTheDude** [comment]
> Must be a joke?

I'd hope but in the Minecraft community, who knows.

**Comment by KoxSosen** [comment]
Hello! Thank you for your interest in LibertyBans; Whether an issue is about a bug, or wording, we try to take and handle everything professionally. 

I didn't make the original choice to go for `victim` to refer to punished entities, however I can't disagree with it either even after reading your point. In the English language, to my understanding, `victim` can be rightfully used to represent someone as a "victim of a punishment", or as a "victim of a mute/ban/etc". 

Your suggestion of the word `criminal` has other meanings too, which would not always be correct as well suited terminology here in my opinion. Victim in general is very fitting, and describes the matter very well. For this reason unfortunately I don't think that this change will be implemented; Of course you are free to voice otherwise, or open a PR with some points on why your suggestion would be better suited here.
