### ISSUE TITLE
max-lifetime-minutes how to write values in seconds?

### ISSUE THREAD

**Issue by Playsus1234** [A248/LibertyBans#267]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

max-lifetime-minutes how to write values in seconds?

**Comment by KoxSosen** [comment]
Hello! The `max-lifetime-minutes` database configuration option gets converted into a `Duration` of minutes [here](https://github.com/A248/LibertyBans/blob/3d87760754105c295b5b247c923339c4ba294681/bans-core/src/main/java/space/arim/libertybans/core/database/DatabaseSettings.java#L152), so to my knowledge there is no way to specify a second, or seconds here. But, changing the method would be a fairly easy change here.

Would you mind sharing what is your use-case here, as in using seconds instead of minutes?

**Comment by A248** [comment]
If you want to refresh connections more frequently than a minute, wouldn't that negate most benefits of using a connection pool anyway?

**Comment by A248** [comment]
Closing for the r
