### ISSUE TITLE
Bans not applying on velocity

### ISSUE THREAD

**Issue by tommasobenatti** [A248/LibertyBans#32]
Hi, I freshly installed the plugin on a velocity server, after I banned a player when he tried to rejoin he could rejoin without problems but the player was still in the banlist

**Comment by tommasobenatti** [comment]
Also mutes aren't applying at all, when I mute it he can talk without problems but he is still in the mutelist

**Comment by tommasobenatti** [comment]
Update: downgrading to 0.7.1 fixed the issue

**Comment by A248** [comment]
Thanks, this issue is fixed as of 9af3738ea1ef5f3a5ab2bc7fc884643cf1c0ade3 . The 0.7.4 release contains the fix.

--------------------------------

As for banning offline players, that will work fine provided one of the following is true:
* The player has joined the server since LibertyBans was installed.
* You are using ONLINE mode.

If this isn't the case, please let me know by opening a new issue.

**Comment by tommasobenatti** [comment]
My server is in offline mode

**Comment by A248** [comment]
In that case, the first bullet point has to be true.

If the player you try to ban has joined the server since LibertyBans was installed, you should be able to ban them just fine.
