### ISSUE TITLE
Use name of player ip-banned instead of address in messages

### ISSUE THREAD

**Issue by tommasobenatti** [A248/LibertyBans#33]
I noticed that when ip-banning players it shows the real ip, is there a way to hide it and show the player's nick

**Comment by KoxSosen** [comment]
Hello!

I belive you can customize the messages in the messages config.

**Comment by KoxSosen** [comment]
I can't really remember right now the exect line, but if you give me arouns 12 hours, I could help you to customize it.

**Comment by A248** [comment]
In the current release, `%VICTIM%` will show the IP address and not the username. You can remove this variable from the configuration in order to make it not show the IP address (all the messages are configurable). However, it is not currently possible to show the username of the one banned.

The reason for this is that you are banning an IP address and not a user or username. Any player who has that IP address, or is linked to that IP address according to your address strictness setting, will be banned. There are potentially *multiple* usernames in question. The code reflects this concept and some (minor) rework will be needed to add this feature.

Another question to help me implement this feature: Do you want to use the username or the display name? I've heard "nickname" mean username and I've heard it mean display name. They are two different concepts.

**Comment by tommasobenatti** [comment]
I mean the username

**Comment by A248** [comment]
You can now use the variable `%TARGET%` which will be replaced with the input target user of the command. For example, in `/ban User1 Some reason`, the target is User1.
