### ISSUE TITLE
Compatibility issue with Jpremium

### ISSUE THREAD

**Issue by tommasobenatti** [A248/LibertyBans#40]
After adding Jpremium to my server Libertybans won't work and gives this error
I'm on velocity
https://hastebin.tommasobenatti.dev/apofirosel.properties

**Comment by tommasobenatti** [comment]
I think that a lib relocation is needed

**Comment by tommasobenatti** [comment]
#41

**Comment by A248** [comment]
LibertyBans actually uses an isolated classloader, which is why dependencies aren't relocated. A consequence of this decision is that LibertyBans can see *other plugins'* unrelocated dependencies, but those plugins cannot see LibertyBans' dependencies.

To detect other plugins which fail to relocate dependencies (or use an isolated classloader like LibertyBans does), LibertyBans will attempt to find unrelocated classes from these libraries. You should see a warning like this:

```
An unknown plugin has shaded the library libName but did not relocate it. This may or may not pose problems.
Contact the author of this plugin and tell them to relocate their dependencies. "
Unrelocated class detected was com.zaxxer.hikari.HikariConfig
```

As for JPremium, the incompatibility is with HikariCP, not HSQLDB. JPremium is closed-source, so I downloaded its jar off of one of the piracy sites (BlackSpigot to be precise). Opening up the jar shows a lot of unrelocated dependencies, including:
* slf4j-api
* slf4j-jdk14
* HikariCP
* javax-mail
* com.sun.mail
* javax-activation
* com.sun.activation

Because the classloader of HikariCP is JPremium's ClassLoader, JPremium's HikariCP cannot see LibertyBans' HSQLDB. Hence the ClassNotFoundException you see.

**Comment by A248** [comment]
I'm going to close this now. If you need me to talk to the JPremium author about the issue, I can. Since you are familiar with the maven-shade-plugin and dependency relocation, I assume that you don't need me to.
