### ISSUE TITLE
/alts doesnt exist

### ISSUE THREAD

**Issue by BumbleTree** [A248/LibertyBans#57]
Commits and documentation mention /alts being added however running that states no such command

Running on Velocity
Using build #47 (Build with weeks added as duration)

**Comment by A248** [comment]
There are two points here of note. First, there is actually a bug where I forgot to register /alts. That's now fixed with the shown commit, so thanks for the report.

Second, LibertyBans really uses `/libertybans` as its main command. All other commands are sub-commands of that command, for example, `/libertybans ban`. Aliases can be configured using the commands.aliases setting in the config.yml. I wasn't sure if you were aware of this, but it's good to mention in case you weren't.
