### ISSUE TITLE
Operator and Victim become -NameUnknown- after server restart (Migration from AdvancedBan)

### ISSUE THREAD

**Issue by D3adhkwen** [A248/LibertyBans#61]
After importing from AdvancedBan's default database, all the names of operator and victim are present. However, after a server restart, all of them become -Name-Unknown-.

Server Type: OFFLINE
Server Version: Velocity 3.0.1 Dev
LibertyBans version: 0.8.0 Snapshot - ee136c9fea6349d6a9d47ab5fb52d3ce3b112004

Import logs: https://pastebin.com/QSf6CkH4
Ingame banlist: 
![image](https://user-images.githubusercontent.com/38313757/129292730-1e3b1540-6e0a-443b-8954-fd770ab82f94.png)

**Comment by A248** [comment]
Thanks, the bug is fixed now.

For your particular case, you have two options to bring names to the banlist. The first option is to simply delete the imported data and re-run the import.

Secondly, you can run another import, on the same AdvancedBan data, and route it to a temporary database, then copy the specific name data to the main database. This requires MySQL/MariaDB as well as another server to do this on. The advantage of this approach is that you will need zero downtime if done correctly.

Here are the steps:
1. Make a new database in MySQL/MariaDB. Let's call it "tempdatabase"
2. Create a temporary server with LibertyBans installed. Configure this LibertyBans to use "tempdatabase".
3. If AdvancedBan uses HSQLDB, you will also need to copy the AdvancedBan plugin folder to this server.
4. Run the import using this temporary server.
5. (Optional) Verify on this temporary server that the banlist has the display you want.
6. Now you will copy the imported data from "tempdatabase" to your main database. Let's call your main database "maindatabase".
7. Log in to MariaDB/MySQL using the command-line, i.e. `mariadb -u <youruser>` or `mysql -u <youruser>`.
8. Run the following SQL: `INSERT INTO maindatabase.libertybans_names SELECT FROM tempdatabase.libertybans_names`. Remember that the main database is "maindatabase".
9. Verify on the main server that the banlist has the display you want.

If you need assistance with this process, feel free to contact me over discord. I will do you a one-time favor since I was responsible for this bug.
