### ISSUE TITLE
Show banned alts on staff login

### ISSUE THREAD

**Issue by BumbleTree** [A248/LibertyBans#72]
Show alt accounts from banned players that joined when the staff member was offline, when they log into the game. So staff cant miss it

**Comment by A248** [comment]
I'm closing this for the mentioned reason that it seems to fall in the scope of another plugin rather than LibertyBans.

Do re-open this if you have a different opinion or good reason for this to be in LibertyBans.

**Comment by WarnDa** [comment]
I just checked this ticket because I wanted the same things.
(I used litebans before and it has this feature, it's awesome to check alts of banned players).

So I searched a plugin like your "StaffCommands".
But it's not useful, as it justs tell you "yes he got other account" but it doesn't tell his they are banned or not (as it's not hooked into LibertyBans)

So for me this feature is important and very useful !
