### ISSUE TITLE
Document database schema

### ISSUE THREAD

**Issue by AuroraLS3** [A248/LibertyBans#78]
Hello,

I recently implemented support for LibertyBans data on my plugin since it was requested.

Another request was made to add support for ban history - Could a copy of database schema be documented similar to [how Litebans does it](https://gitlab.com/ruany/LiteBansAPI/-/wikis/Database-Structure)? Thanks

**Comment by A248** [comment]
If you are writing a plugin for Bukkit, BungeeCord, or Velocity, I **strongly encourage** you to use the LibertyBans API rather than contacting the database directly. The Java API is semantically versioned according to [this policy](https://github.com/A248/LibertyBans/wiki/Versioning-and-Support-Policies) and provides much more stability than directly using the database schema.

Nevertheless, if you must use the database schema, you can easily find it in the source code. For example: https://github.com/A248/LibertyBans/search?q=CREATE+TABLE+libertybans_bans

There is also a wiki page with extra information on the database schema: https://github.com/A248/LibertyBans/wiki/The-Database-Schema
