### ISSUE TITLE
Feature -s (silent) and second/seconds 

### ISSUE THREAD

**Issue by MrTokyo12345** [A248/LibertyBans#85]
This is to do a silent command ban/mute/kick/warn, which I can only see the various staff.

And added text type
miute/minutes, second/seconds

**Comment by A248** [comment]
The silent feature is already implemented; however, it's only available in development builds. The next stable release of LibertyBans (0.8.1) will include the silent feature. You can find more information about how to use this feature on the wiki.

While it is already possible to ban in minutes, I haven't found good reason to ban people for seconds. The feature has been suggested before, but implementing it creates some minor annoyances for me to deal with. I've avoided it because I don't want to commit to guaranteeing such fine precision for timespans.
